/**
 * Frame-animated rendering for the kitty theme's cat, drawn from real sprite
 * sheets (Craftpix "Cat" pack, character #11) instead of hand-drawn shapes. Each
 * sheet is a horizontal strip of equal-width frames; the cat's physics still live
 * in catSprite.ts and this just picks an animation + frame for the current state
 * and blits it, flipped for leftward travel.
 *
 * Four clips are used:
 * - **walk** — while roaming and moving.
 * - **idle** — while paused mid-roam or recovering after a pounce.
 * - **jump** — the crouch wind-up and the airborne pounce, scrubbed by progress.
 * - **hit** — a mallet whack played when the cat catches the yarn; the smack that
 *   flings the ball is fired at the impact frame (see catSprite.ts `hit` state).
 *
 * Each clip was packed to its own tight crop box, so frame sizes + the cat-body
 * anchor differ per clip; {@link CLIP_META} (generated by the build, see the
 * handoff) records them, and a shared {@link BASE_SCALE} keeps the cat one
 * consistent on-screen size across clips. Needs a live 2d context + loaded
 * images, so it's covered by the component/e2e tests, not jsdom units.
 */
import walkUrl from './cat/walk.png';
import idleUrl from './cat/idle.png';
import jumpUrl from './cat/jump.png';
import hitUrl from './cat/hit.png';
import { CROUCH_TIME, HIT_TIME, type Cat } from './catSprite';

/** Per-clip frame geometry, generated by the spritesheet build. */
interface ClipMeta {
  /** One frame's width / height in the packed strip (px). */
  frameW: number;
  frameH: number;
  /** Frames in the strip. */
  count: number;
  /** The cat's body-centre within a frame (px) — aligned to cat.x / cat.y. */
  anchorX: number;
  anchorY: number;
}

type ClipName = 'walk' | 'idle' | 'jump' | 'hit';

export const CLIP_META: Record<ClipName, ClipMeta> = {
  walk: { frameW: 127, frameH: 130, count: 20, anchorX: 61, anchorY: 63 },
  idle: { frameW: 123, frameH: 125, count: 20, anchorX: 61, anchorY: 57 },
  jump: { frameW: 125, frameH: 179, count: 20, anchorX: 61, anchorY: 111 },
  hit: { frameW: 319, frameH: 206, count: 17, anchorX: 115, anchorY: 139 },
};

/**
 * Base scale the stored frames are drawn at on a desktop viewport (cat body
 * ≈ 115px tall). The live draw scale is this times the viewport scale (see
 * {@link viewScale}), so the cat shrinks on a narrow phone instead of dominating
 * it. Exported so KittyBackground can derive the matching hammer reach + speeds.
 */
export const BASE_SCALE = 0.92;

/**
 * Where the mallet head lands at the swing's impact frame, relative to the cat's
 * body anchor, for a given draw `scale`. The Hit clip is a long-handled overhead
 * whack: at frame 8 the hammer head comes down ≈150 stored px right and ≈16 down
 * of the body anchor (115,139). Kept in *stored* sprite px and scaled by the live
 * draw scale so it tracks the cat's on-screen size automatically (re-measure only
 * if the hit timing or crop changes). x flips with `cat.facing`. The pure cat
 * model stays free of this render constant — KittyBackground passes it in as
 * `opts`.
 */
export function hammerReach(scale: number): { x: number; y: number } {
  return { x: 150 * scale, y: 16 * scale };
}

/** Loop rates for the cyclic clips (frames/second). */
const WALK_FPS = 16;
const IDLE_FPS = 9;
/** Jump frames spent on the crouch wind-up before the airborne run. */
const JUMP_WINDUP_FRAMES = 6;

/** One loaded strip plus its geometry. */
interface Sheet {
  img: HTMLImageElement;
  meta: ClipMeta;
}

/** The four loaded clips. */
export interface CatSheets {
  walk: Sheet;
  idle: Sheet;
  jump: Sheet;
  hit: Sheet;
}

/** Kick off loading the four sprite strips (browser only). */
export function loadCatSheets(): CatSheets {
  const mk = (src: string, name: ClipName): Sheet => {
    const img = new Image();
    img.src = src;
    return { img, meta: CLIP_META[name] };
  };
  return {
    walk: mk(walkUrl, 'walk'),
    idle: mk(idleUrl, 'idle'),
    jump: mk(jumpUrl, 'jump'),
    hit: mk(hitUrl, 'hit'),
  };
}

/** Pick the clip + frame index for the cat's current state. */
function pickFrame(cat: Cat, sheets: CatSheets): { sheet: Sheet; index: number } {
  switch (cat.state) {
    case 'crouch': {
      const p = Math.min(1, cat.stateTime / CROUCH_TIME);
      return { sheet: sheets.jump, index: Math.floor(p * (JUMP_WINDUP_FRAMES - 1)) };
    }
    case 'pounce': {
      // Scrub the airborne frames by how far through the leap we are.
      let p = 1;
      if (cat.leapDist0 > 1) {
        const d = Math.hypot(cat.targetX - cat.x, cat.targetY - cat.y);
        p = Math.min(1, Math.max(0, 1 - d / cat.leapDist0));
      }
      const span = sheets.jump.meta.count - 1 - JUMP_WINDUP_FRAMES;
      return { sheet: sheets.jump, index: JUMP_WINDUP_FRAMES + Math.round(p * span) };
    }
    case 'hit': {
      // Play the mallet swing once across the whole hit state.
      const p = Math.min(1, cat.stateTime / HIT_TIME);
      const n = sheets.hit.meta.count;
      return { sheet: sheets.hit, index: Math.min(n - 1, Math.floor(p * (n - 1))) };
    }
    case 'recover':
      return { sheet: sheets.idle, index: Math.floor(cat.phase * IDLE_FPS) % sheets.idle.meta.count };
    default: {
      // Roam: walk while moving, idle when dawdling at a spot.
      const moving = Math.hypot(cat.vx, cat.vy) > 1;
      const sheet = moving ? sheets.walk : sheets.idle;
      const fps = moving ? WALK_FPS : IDLE_FPS;
      return { sheet, index: Math.floor(cat.phase * fps) % sheet.meta.count };
    }
  }
}

/**
 * Draw the cat at its current position, facing, and animation frame. No-op until
 * the relevant strip has decoded (avoids a flash of broken-image on first paint).
 */
export function drawCatSheet(
  ctx: CanvasRenderingContext2D,
  cat: Cat,
  sheets: CatSheets,
  scale: number = BASE_SCALE,
): void {
  const { sheet, index } = pickFrame(cat, sheets);
  const { img, meta } = sheet;
  if (!img.complete || img.naturalWidth === 0) return;

  const dw = meta.frameW * scale;
  const dh = meta.frameH * scale;

  ctx.save();
  ctx.translate(Math.round(cat.x), Math.round(cat.y));
  ctx.scale(cat.facing, 1); // mirror the right-facing art for leftward travel
  // Anchor the cat's body centre at the origin so clips with different crop
  // boxes (e.g. the wide hit frame) still line up on cat.x / cat.y.
  ctx.drawImage(
    img,
    index * meta.frameW,
    0,
    meta.frameW,
    meta.frameH,
    -meta.anchorX * scale,
    -meta.anchorY * scale,
    dw,
    dh,
  );
  ctx.restore();
}
